trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
- group: FinShield-Frontend-StaticWebApp

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'

  - script: |
      cd finshield-frontend
      npm install
      npm run build
    displayName: 'Build frontend'

  - task: AzureStaticWebApp@0
    inputs:
      app_location: 'finshield-frontend'
      output_location: 'dist'
      azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN)